spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  thymeleaf:
    cache: false

logging.level:
  org.hibernate.SQL: debug